name: CI

on:
  push:
    tags-ignore:
      - "*"
  workflow_call:

jobs:
  lint:
    name : Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: mypy
        run: uv run mypy --output json src | uv run scripts/mypy-gha.py
      - name: ruff check
        run: uv run ruff check --output-format=github .
      - name: ruff format
        run: uv run ruff format --check .

  test:
    name: Test - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - run: uv run pytest
